name: Build and Test

# This workflow is triggered whenever a pull request is made to the "dev" branch
on: 
  pull_request: 
    branches:
      - dev

# The workflow consists of one job
jobs:
  build-and-test:
    # The job will run on an virtual machine with the latest Ubuntu image
    runs-on: ubuntu-latest

    # The steps that will be executed in the job
    steps: 

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app:latest ./api #funkar på samma sätt som det vi skriver i terminalen# 
        # version (my-app:latest) är inte ett måste men bra att ha med så skapas nya images per version #
        #t.ex. my-app:1.0, my-app:1.2 osv. #
        #går nåt snett med den senaste imagen så har vi versioner sparade att kolla bakåt i vad som gick fel#
        #*latest används aldrig i produktionsmiljö"
      
      - name: Run tests
        run: docker run --rm my-api:latest npm test # --rm gör så att containern raderas efter testet körs oavasett lyckas eller misslyckas#
        #varför ta bort? om vi kör ganska tunga tester och inte tar bort dessa utan fortsatt pipelinen i flera steg så blir det långsammare #
        # det enda syftet var att testa, så resurser ska inte gå åt att låta testerna finnas kvar då man bara villveta hur de gick#

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag image for Docker Hub
        run: docker tag my-api:latest ${{ secrets.DOCKER_USERNAME }}/my-api:latest # bra att använda dynamisk variabel för att man ska kunna byta konton genom att ändra secret direkt, slipper arbeta dubbelt och ändra i pipelinen 


build-frontend:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install depend and build frontend
      run: 
        cd frontend
        npm install 
        npm run build

    - name: Build frontend image
      run: docker build -t my-frontend:latest ./frontend

        #slut på genomgång onsdag#
