name: Build and Test

# This workflow is triggered whenever a pull request is made to the "dev" branch
on: 
  pull_request: 
    branches:
      - dev

# The workflow consists of one job
jobs:
  build-and-test:
    # The job will run on an virtual machine with the latest Ubuntu image
    runs-on: ubuntu-latest

    # The steps that will be executed in the job
    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Verify Docker Compose is installed
      - name: Set up Docker Compose
        run: docker compose --version

      # 3️⃣ Build all services defined in docker-compose.yml
      - name: Build Docker services
        run: docker compose build

      # 4️⃣ Run backend tests inside API service
      - name: Run API tests
        run: docker compose run --rm api npm test

      # 5️⃣ Build frontend image (production)
      - name: Build frontend image
        run: docker compose build frontend

      # 6️⃣ Log in to Docker Hub (optional, for pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ Push backend and frontend images (optional)
      - name: Push backend image
        run: docker compose push api

      - name: Push frontend image
        run: docker compose push frontend